---
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_14_todo_live
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres